/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_mark_openvideo_myNDK */

#ifndef _Included_com_example_mark_openvideo_myNDK
#define _Included_com_example_mark_openvideo_myNDK
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_mark_openvideo_myNDK
 * Method:    imgProcess
 * Signature: (JJ)V
 */
JNIEXPORT jint JNICALL Java_com_example_mark_openvideo_myNDK_imgProcess
  (JNIEnv *, jobject, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
